name: berry
description: Dependency injection container.
version: 0.0.1
homepage: https://github.com/criticalbh/berry
author: admirsabanovic <admir_sabanovic@live.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
   graphs: ^0.2.0

dev_dependencies:
  test: ^1.5.1
